"""Reference data: competitions and clubs with aliases and brand colours.

Aliases feed the team normalizer, so every naming variant a source might use
("Man City", "MCI", "Manchester City FC") resolves to the same team.
"""

COMPETITIONS = [
    # slug, code, name, short_name, country, priority, aliases
    ("champions-league", "CL", "UEFA Champions League", "UCL", "Europe", 100,
     ["Champions League", "UCL", "UEFA CL"]),
    ("premier-league", "PL", "Premier League", "Premier League", "England", 95,
     ["English Premier League", "EPL", "Barclays Premier League"]),
    ("la-liga", "PD", "La Liga", "La Liga", "Spain", 90,
     ["LaLiga", "Primera Division", "Primera División", "LaLiga EA Sports"]),
    ("bundesliga", "BL1", "Bundesliga", "Bundesliga", "Germany", 85, ["1. Bundesliga", "German Bundesliga"]),
    ("serie-a", "SA", "Serie A", "Serie A", "Italy", 85, ["Italian Serie A", "Serie A TIM"]),
    ("ligue-1", "FL1", "Ligue 1", "Ligue 1", "France", 80, ["Ligue 1 McDonald's", "French Ligue 1"]),
    ("europa-league", "EL", "UEFA Europa League", "UEL", "Europe", 75, ["Europa League", "UEL"]),
    ("mls", "MLS", "Major League Soccer", "MLS", "USA", 70, ["MLS", "Major League Soccer"]),
]

# slug, name, short_name, tla, country, primary, secondary, popularity, venue, aliases
TEAMS = [
    # Premier League
    ("arsenal", "Arsenal", "Arsenal", "ARS", "England", "#EF0107", "#FFFFFF", 92, "Emirates Stadium",
     ["Arsenal FC", "The Gunners"]),
    ("manchester-city", "Manchester City", "Man City", "MCI", "England", "#6CABDD", "#1C2C5B", 94, "Etihad Stadium",
     ["Man City", "Manchester City FC", "Man. City"]),
    ("manchester-united", "Manchester United", "Man United", "MUN", "England", "#DA291C", "#FBE122", 95, "Old Trafford",
     ["Man Utd", "Man United", "Manchester United FC", "Man U", "MUFC", "Manchester Utd"]),
    ("liverpool", "Liverpool", "Liverpool", "LIV", "England", "#C8102E", "#00B2A9", 94, "Anfield",
     ["Liverpool FC", "LFC"]),
    ("chelsea", "Chelsea", "Chelsea", "CHE", "England", "#034694", "#DBA111", 90, "Stamford Bridge",
     ["Chelsea FC", "CFC"]),
    ("tottenham-hotspur", "Tottenham Hotspur", "Spurs", "TOT", "England", "#FFFFFF", "#132257", 84,
     "Tottenham Hotspur Stadium", ["Tottenham", "Spurs", "Tottenham Hotspur FC", "THFC"]),
    ("newcastle-united", "Newcastle United", "Newcastle", "NEW", "England", "#241F20", "#FFFFFF", 78,
     "St James' Park", ["Newcastle", "Newcastle Utd", "NUFC", "Newcastle United FC"]),
    ("aston-villa", "Aston Villa", "Aston Villa", "AVL", "England", "#670E36", "#95BFE5", 74, "Villa Park",
     ["Villa", "Aston Villa FC"]),
    ("brighton", "Brighton & Hove Albion", "Brighton", "BHA", "England", "#0057B8", "#FFCD00", 68,
     "American Express Stadium", ["Brighton", "Brighton and Hove Albion", "Brighton Hove Albion"]),
    ("west-ham-united", "West Ham United", "West Ham", "WHU", "England", "#7A263A", "#1BB1E7", 70, "London Stadium",
     ["West Ham", "West Ham Utd", "West Ham United FC"]),
    ("everton", "Everton", "Everton", "EVE", "England", "#003399", "#FFFFFF", 68, "Hill Dickinson Stadium",
     ["Everton FC"]),
    ("nottingham-forest", "Nottingham Forest", "Nott'm Forest", "NFO", "England", "#DD0000", "#FFFFFF", 64,
     "City Ground", ["Nottingham Forest FC", "Nott'm Forest", "Notts Forest", "Forest"]),
    # La Liga
    ("real-madrid", "Real Madrid", "Real Madrid", "RMA", "Spain", "#FFFFFF", "#00529F", 98, "Santiago Bernabéu",
     ["Real Madrid CF", "Madrid", "R. Madrid"]),
    ("barcelona", "Barcelona", "Barça", "BAR", "Spain", "#A50044", "#004D98", 97, "Spotify Camp Nou",
     ["FC Barcelona", "Barça", "Barca"]),
    ("atletico-madrid", "Atlético Madrid", "Atleti", "ATM", "Spain", "#CB3524", "#272E61", 84,
     "Riyadh Air Metropolitano", ["Atletico Madrid", "Atlético de Madrid", "Club Atlético de Madrid", "Atleti",
                                  "Atl. Madrid"]),
    ("sevilla", "Sevilla", "Sevilla", "SEV", "Spain", "#D81920", "#FFFFFF", 66, "Ramón Sánchez-Pizjuán",
     ["Sevilla FC", "Seville"]),
    ("real-sociedad", "Real Sociedad", "Real Sociedad", "RSO", "Spain", "#0067B1", "#FFFFFF", 62, "Reale Arena",
     ["Real Sociedad de Fútbol", "La Real"]),
    ("villarreal", "Villarreal", "Villarreal", "VIL", "Spain", "#FFE667", "#005187", 62, "Estadio de la Cerámica",
     ["Villarreal CF"]),
    ("athletic-club", "Athletic Club", "Athletic", "ATH", "Spain", "#EE2523", "#FFFFFF", 64, "San Mamés",
     ["Athletic Bilbao", "Athletic Club Bilbao"]),
    ("real-betis", "Real Betis", "Betis", "BET", "Spain", "#00954C", "#FFFFFF", 62, "Benito Villamarín",
     ["Real Betis Balompié", "Betis"]),
    # Bundesliga
    ("bayern-munich", "Bayern Munich", "Bayern", "FCB", "Germany", "#DC052D", "#0066B2", 92, "Allianz Arena",
     ["FC Bayern München", "Bayern München", "FC Bayern", "Bayern", "Bayern Munchen"]),
    ("borussia-dortmund", "Borussia Dortmund", "Dortmund", "BVB", "Germany", "#FDE100", "#000000", 85,
     "Signal Iduna Park", ["Dortmund", "BVB", "B. Dortmund"]),
    ("bayer-leverkusen", "Bayer Leverkusen", "Leverkusen", "B04", "Germany", "#E32221", "#000000", 76, "BayArena",
     ["Bayer 04 Leverkusen", "Leverkusen"]),
    ("rb-leipzig", "RB Leipzig", "Leipzig", "RBL", "Germany", "#DD0741", "#001F47", 70, "Red Bull Arena",
     ["RasenBallsport Leipzig", "Leipzig"]),
    ("eintracht-frankfurt", "Eintracht Frankfurt", "Frankfurt", "SGE", "Germany", "#E1000F", "#000000", 66,
     "Deutsche Bank Park", ["Frankfurt", "E. Frankfurt"]),
    ("vfb-stuttgart", "VfB Stuttgart", "Stuttgart", "VFB", "Germany", "#E32219", "#FFFFFF", 62, "MHPArena",
     ["Stuttgart"]),
    ("vfl-wolfsburg", "VfL Wolfsburg", "Wolfsburg", "WOB", "Germany", "#65B32E", "#FFFFFF", 56, "Volkswagen Arena",
     ["Wolfsburg"]),
    ("borussia-monchengladbach", "Borussia Mönchengladbach", "Gladbach", "BMG", "Germany", "#00B140", "#000000",
     60, "Borussia-Park", ["Mönchengladbach", "Monchengladbach", "Gladbach", "M'gladbach"]),
    # Serie A
    ("inter", "Inter", "Inter", "INT", "Italy", "#0068A8", "#000000", 86, "San Siro",
     ["Inter Milan", "FC Internazionale Milano", "Internazionale", "Inter Milano"]),
    ("juventus", "Juventus", "Juventus", "JUV", "Italy", "#F2F2F2", "#000000", 88, "Allianz Stadium",
     ["Juventus FC", "Juve"]),
    ("ac-milan", "AC Milan", "Milan", "ACM", "Italy", "#FB090B", "#000000", 86, "San Siro",
     ["Milan", "AC Milan"]),
    ("napoli", "Napoli", "Napoli", "NAP", "Italy", "#12A0D7", "#FFFFFF", 80, "Stadio Diego Armando Maradona",
     ["SSC Napoli"]),
    ("roma", "Roma", "Roma", "ROM", "Italy", "#8E1F2F", "#F0BC42", 76, "Stadio Olimpico", ["AS Roma"]),
    ("lazio", "Lazio", "Lazio", "LAZ", "Italy", "#87D8F7", "#FFFFFF", 68, "Stadio Olimpico", ["SS Lazio"]),
    ("atalanta", "Atalanta", "Atalanta", "ATA", "Italy", "#1E71B8", "#000000", 68, "Gewiss Stadium",
     ["Atalanta BC"]),
    ("fiorentina", "Fiorentina", "Fiorentina", "FIO", "Italy", "#482E92", "#FFFFFF", 62, "Stadio Artemio Franchi",
     ["ACF Fiorentina"]),
    # Ligue 1
    ("paris-saint-germain", "Paris Saint-Germain", "PSG", "PSG", "France", "#004170", "#DA291C", 90,
     "Parc des Princes", ["Paris Saint-Germain FC", "PSG", "Paris SG", "Paris"]),
    ("marseille", "Marseille", "Marseille", "MAR", "France", "#2FAEE0", "#FFFFFF", 70, "Orange Vélodrome",
     ["Olympique de Marseille", "OM"]),
    ("lyon", "Lyon", "Lyon", "LYO", "France", "#DA001A", "#1B3C8C", 66, "Groupama Stadium",
     ["Olympique Lyonnais", "OL"]),
    ("monaco", "Monaco", "Monaco", "ASM", "France", "#E51B22", "#FFFFFF", 64, "Stade Louis II", ["AS Monaco"]),
    ("lille", "Lille", "Lille", "LIL", "France", "#E01E13", "#24216A", 60, "Decathlon Arena", ["Lille OSC", "LOSC"]),
    ("nice", "Nice", "Nice", "NIC", "France", "#C8102E", "#000000", 58, "Allianz Riviera", ["OGC Nice"]),
    # MLS
    ("inter-miami", "Inter Miami", "Inter Miami", "MIA", "USA", "#F7B5CD", "#231F20", 82, "Chase Stadium",
     ["Inter Miami CF", "Miami"]),
    ("la-galaxy", "LA Galaxy", "LA Galaxy", "LAG", "USA", "#00245D", "#FFD200", 66, "Dignity Health Sports Park",
     ["Los Angeles Galaxy", "Galaxy"]),
    ("lafc", "LAFC", "LAFC", "LAF", "USA", "#C39E6D", "#000000", 64, "BMO Stadium", ["Los Angeles FC", "LA FC"]),
    ("seattle-sounders", "Seattle Sounders", "Seattle", "SEA", "USA", "#5D9741", "#236192", 60, "Lumen Field",
     ["Seattle Sounders FC", "Seattle"]),
    ("atlanta-united", "Atlanta United", "Atlanta", "ATL", "USA", "#80000A", "#A29061", 58, "Mercedes-Benz Stadium",
     ["Atlanta United FC", "Atlanta"]),
    ("new-york-city-fc", "New York City FC", "NYCFC", "NYC", "USA", "#6CACE4", "#041E42", 58, "Yankee Stadium",
     ["NYCFC", "NYC FC"]),
    ("columbus-crew", "Columbus Crew", "Columbus", "CLB", "USA", "#FEDD00", "#000000", 54, "ScottsMiracle-Gro Field",
     ["Crew", "Columbus"]),
    ("austin-fc", "Austin FC", "Austin", "ATX", "USA", "#00B140", "#000000", 52, "Q2 Stadium", ["Austin"]),
    # Europe extras
    ("porto", "FC Porto", "Porto", "POR", "Portugal", "#00428C", "#FFFFFF", 70, "Estádio do Dragão", ["Porto"]),
]

# Which clubs play in which competition (used by the demo schedule generator).
COMPETITION_TEAMS = {
    "PL": ["arsenal", "manchester-city", "manchester-united", "liverpool", "chelsea", "tottenham-hotspur",
           "newcastle-united", "aston-villa", "brighton", "west-ham-united", "everton", "nottingham-forest"],
    "PD": ["real-madrid", "barcelona", "atletico-madrid", "sevilla", "real-sociedad", "villarreal",
           "athletic-club", "real-betis"],
    "BL1": ["bayern-munich", "borussia-dortmund", "bayer-leverkusen", "rb-leipzig", "eintracht-frankfurt",
            "vfb-stuttgart", "vfl-wolfsburg", "borussia-monchengladbach"],
    "SA": ["inter", "juventus", "ac-milan", "napoli", "roma", "lazio", "atalanta", "fiorentina"],
    "FL1": ["paris-saint-germain", "marseille", "lyon", "monaco", "lille", "nice"],
    "MLS": ["inter-miami", "la-galaxy", "lafc", "seattle-sounders", "atlanta-united", "new-york-city-fc",
            "columbus-crew", "austin-fc"],
    "CL": ["real-madrid", "barcelona", "bayern-munich", "manchester-city", "arsenal", "liverpool", "inter",
           "paris-saint-germain"],
    "EL": ["manchester-united", "tottenham-hotspur", "roma", "lazio", "lyon", "real-betis", "eintracht-frankfurt",
           "porto"],
}

# Crest images for the seeded clubs. European clubs use the football-data.org crest CDN (the same
# URLs its API returns), MLS clubs use ESPN's. The UI falls back to a generated badge if one fails.
TEAM_LOGOS = {
    "arsenal": "https://crests.football-data.org/57.png",
    "aston-villa": "https://crests.football-data.org/58.png",
    "chelsea": "https://crests.football-data.org/61.png",
    "everton": "https://crests.football-data.org/62.png",
    "liverpool": "https://crests.football-data.org/64.png",
    "manchester-city": "https://crests.football-data.org/65.png",
    "manchester-united": "https://crests.football-data.org/66.png",
    "newcastle-united": "https://crests.football-data.org/67.png",
    "tottenham-hotspur": "https://crests.football-data.org/73.png",
    "west-ham-united": "https://crests.football-data.org/563.png",
    "brighton": "https://crests.football-data.org/397.png",
    "nottingham-forest": "https://crests.football-data.org/351.png",
    "real-madrid": "https://crests.football-data.org/86.png",
    "barcelona": "https://crests.football-data.org/81.png",
    "atletico-madrid": "https://crests.football-data.org/78.png",
    "sevilla": "https://crests.football-data.org/559.png",
    "real-sociedad": "https://crests.football-data.org/92.png",
    "villarreal": "https://crests.football-data.org/94.png",
    "athletic-club": "https://crests.football-data.org/77.png",
    "real-betis": "https://crests.football-data.org/90.png",
    "bayern-munich": "https://crests.football-data.org/5.png",
    "borussia-dortmund": "https://crests.football-data.org/4.png",
    "bayer-leverkusen": "https://crests.football-data.org/3.png",
    "rb-leipzig": "https://crests.football-data.org/721.png",
    "eintracht-frankfurt": "https://crests.football-data.org/19.png",
    "vfb-stuttgart": "https://crests.football-data.org/10.png",
    "vfl-wolfsburg": "https://crests.football-data.org/11.png",
    "borussia-monchengladbach": "https://crests.football-data.org/18.png",
    "inter": "https://crests.football-data.org/108.png",
    "juventus": "https://crests.football-data.org/109.png",
    "ac-milan": "https://crests.football-data.org/98.png",
    "napoli": "https://crests.football-data.org/113.png",
    "roma": "https://crests.football-data.org/100.png",
    "lazio": "https://crests.football-data.org/110.png",
    "atalanta": "https://crests.football-data.org/102.png",
    "fiorentina": "https://crests.football-data.org/99.png",
    "paris-saint-germain": "https://crests.football-data.org/524.png",
    "marseille": "https://crests.football-data.org/516.png",
    "lyon": "https://crests.football-data.org/523.png",
    "monaco": "https://crests.football-data.org/548.png",
    "lille": "https://crests.football-data.org/521.png",
    "nice": "https://crests.football-data.org/522.png",
    "porto": "https://crests.football-data.org/503.png",
    "inter-miami": "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png",
    "la-galaxy": "https://a.espncdn.com/i/teamlogos/soccer/500/187.png",
    "lafc": "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png",
    "seattle-sounders": "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png",
    "atlanta-united": "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png",
    "new-york-city-fc": "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png",
    "columbus-crew": "https://a.espncdn.com/i/teamlogos/soccer/500/183.png",
    "austin-fc": "https://a.espncdn.com/i/teamlogos/soccer/500/20906.png",
}

# How prominent a club or national team is, 0-100, for teams that arrive from fixture feeds
# rather than the seed list above. Only used to rank the featured match and live lists.
TEAM_POPULARITY = {
    # national teams
    "Brazil": 95, "Argentina": 95, "France": 92, "England": 92, "Spain": 92, "Germany": 90, "Portugal": 90,
    "Italy": 88, "Netherlands": 86, "Belgium": 80, "Croatia": 78, "Uruguay": 76, "Mexico": 75, "United States": 75,
    "USA": 75, "Colombia": 72, "Morocco": 72, "Denmark": 70, "Switzerland": 68, "Japan": 68, "Norway": 66,
    "Senegal": 65, "Poland": 65, "Serbia": 62, "Austria": 62, "Turkey": 62, "Sweden": 62, "Canada": 62,
    "Nigeria": 62, "Egypt": 62, "South Korea": 62, "Chile": 60, "Ecuador": 60, "Scotland": 60, "Wales": 60,
    "Ukraine": 60, "Greece": 58, "Czechia": 58, "Australia": 58, "Ghana": 58, "Cameroon": 58, "Ivory Coast": 58,
    "Algeria": 56, "Saudi Arabia": 55, "Iran": 55, "Peru": 55, "Paraguay": 52, "Tunisia": 52, "Hungary": 55,
    "Republic of Ireland": 54, "Northern Ireland": 50, "Slovakia": 50, "Slovenia": 50, "Romania": 52,
    # well-known clubs outside the seeded leagues
    "Benfica": 74, "Sporting CP": 70, "Ajax": 72, "PSV Eindhoven": 66, "Feyenoord": 66, "Celtic": 68, "Rangers": 64,
    "Galatasaray": 70, "Fenerbahce": 68, "Besiktas": 60, "Al Nassr": 72, "Al Hilal": 70, "Al Ittihad": 62,
    "Flamengo": 74, "Palmeiras": 70, "Corinthians": 66, "Sao Paulo": 62, "Santos": 62, "Boca Juniors": 76,
    "River Plate": 74, "Club America": 66, "Chivas": 62, "Monterrey": 58, "Tigres UANL": 58,
}
