/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check */
        get: operations["check_api_admin_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Links */
        get: operations["links_api_admin_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Matches */
        get: operations["admin_matches_api_admin_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_admin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_admin_sources__key__patch"];
        trace?: never;
    };
    "/api/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competitions */
        get: operations["competitions_api_competitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competitions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competition Detail */
        get: operations["competition_detail_api_competitions__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competitions/{slug}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competition Table */
        get: operations["competition_table_api_competitions__slug__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Links */
        post: operations["validate_links_api_links_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches */
        get: operations["matches_api_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Matches */
        get: operations["live_matches_api_matches_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Matches */
        post: operations["sync_matches_api_matches_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming Matches */
        get: operations["upcoming_matches_api_matches_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match Detail */
        get: operations["match_detail_api_matches__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{ref}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match Details
         * @description Line-ups, key events, team stats and recent form, when the fixture feed has them.
         */
        get: operations["match_details_api_matches__ref__details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{ref}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match Sources */
        get: operations["match_sources_api_matches__ref__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Sources */
        post: operations["run_sources_api_sources_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams */
        get: operations["teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Detail */
        get: operations["team_detail_api_teams__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompetitionOut */
        CompetitionOut: {
            /** Code */
            code: string | null;
            /** Country */
            country: string | null;
            /** Id */
            id: number;
            /** Is Major */
            is_major: boolean;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /**
             * National Teams
             * @default false
             */
            national_teams: boolean;
            /** Short Name */
            short_name: string | null;
            /** Slug */
            slug: string;
        };
        /** CompetitionWithCounts */
        CompetitionWithCounts: {
            /** Code */
            code: string | null;
            /** Country */
            country: string | null;
            /** Id */
            id: number;
            /** Is Major */
            is_major: boolean;
            /** Live Count */
            live_count: number;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /**
             * National Teams
             * @default false
             */
            national_teams: boolean;
            /** Short Name */
            short_name: string | null;
            /** Slug */
            slug: string;
            /** Upcoming Count */
            upcoming_count: number;
        };
        /** EventOut */
        EventOut: {
            /** Assist */
            assist?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "goal" | "own_goal" | "penalty_goal" | "missed_penalty" | "yellow" | "red" | "sub" | "period";
            /** Label */
            label?: string | null;
            /** Minute */
            minute: string | null;
            /** Player */
            player?: string | null;
            /** Score */
            score?: string | null;
            /** Side */
            side: ("home" | "away") | null;
        };
        /** Featured */
        Featured: {
            match: components["schemas"]["MatchOut"] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "next" | "always_on";
        };
        /** FormGame */
        FormGame: {
            /** Date */
            date: string | null;
            /** Home */
            home: boolean;
            /** Opponent */
            opponent: string;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "D" | "L";
            /** Score */
            score: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeOut */
        HomeOut: {
            /** Competitions */
            competitions: components["schemas"]["CompetitionWithCounts"][];
            /** Demo Mode */
            demo_mode: boolean;
            featured: components["schemas"]["Featured"];
            /** Live */
            live: components["schemas"]["MatchOut"][];
            /** Next Matches */
            next_matches: components["schemas"]["MatchOut"][];
            /** Popular Teams */
            popular_teams: components["schemas"]["TeamOut"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** LineupOut */
        LineupOut: {
            /** Formation */
            formation: string | null;
            /** Lines */
            lines: components["schemas"]["PlayerOut"][][] | null;
            /** Starters */
            starters: components["schemas"]["PlayerOut"][];
            /** Subs */
            subs: components["schemas"]["PlayerOut"][];
        };
        /** MatchDetailsOut */
        MatchDetailsOut: {
            /** Attendance */
            attendance?: number | null;
            /** Available */
            available: boolean;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["EventOut"][];
            /** Form */
            form?: {
                [key: string]: components["schemas"]["FormGame"][];
            } | null;
            /** Lineups */
            lineups?: {
                [key: string]: components["schemas"]["LineupOut"];
            } | null;
            /**
             * Stats
             * @default []
             */
            stats: components["schemas"]["StatOut"][];
        };
        /** MatchOut */
        MatchOut: {
            away: components["schemas"]["TeamOut"];
            competition: components["schemas"]["CompetitionOut"] | null;
            home: components["schemas"]["TeamOut"];
            /** Id */
            id: number;
            /** Is Live */
            is_live: boolean;
            /**
             * Kickoff Time
             * Format: date-time
             */
            kickoff_time: string;
            /** Minute */
            minute: number | null;
            /** Minute Display */
            minute_display: string | null;
            /** Referee */
            referee: string | null;
            score: components["schemas"]["Score"] | null;
            /** Slug */
            slug: string;
            sources: components["schemas"]["SourceSummary"];
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "live" | "halftime" | "finished" | "postponed" | "suspended" | "cancelled";
            /** Venue */
            venue: string | null;
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** MatchSources */
        MatchSources: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Country */
            country?: string | null;
            /** Items */
            items: components["schemas"]["SourceLinkOut"][];
            /** Match Id */
            match_id: number;
            summary: components["schemas"]["SourceSummary"];
        };
        /** MetaOut */
        MetaOut: {
            /** Demo Mode */
            demo_mode: boolean;
            /** Name */
            name: string;
            /** Refresh Seconds */
            refresh_seconds: {
                [key: string]: number;
            };
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Version */
            version: string;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Author */
            author: string | null;
            /** License */
            license: string | null;
            /** License Url */
            license_url: string | null;
            /** Page */
            page: string | null;
            /** Subject */
            subject: string | null;
            /** Url */
            url: string;
        };
        /** PlayerOut */
        PlayerOut: {
            /**
             * Goals
             * @default 0
             */
            goals: number;
            /** Name */
            name: string;
            /** Number */
            number?: string | null;
            /** Position */
            position?: string | null;
            /**
             * Red
             * @default false
             */
            red: boolean;
            /** Short Name */
            short_name?: string | null;
            /**
             * Subbed In
             * @default false
             */
            subbed_in: boolean;
            /**
             * Subbed Out
             * @default false
             */
            subbed_out: boolean;
            /**
             * Yellow
             * @default false
             */
            yellow: boolean;
        };
        /** Reliability */
        Reliability: {
            /** Checks */
            checks: number;
            /** Label */
            label: string;
            /** Uptime Pct */
            uptime_pct: number | null;
        };
        /** Score */
        Score: {
            /** Away */
            away: number | null;
            /** Home */
            home: number | null;
        };
        /** SearchOut */
        SearchOut: {
            /** Competitions */
            competitions: components["schemas"]["CompetitionOut"][];
            /** Matches */
            matches: components["schemas"]["MatchOut"][];
            /** Query */
            query: string;
            /** Teams */
            teams: components["schemas"]["TeamOut"][];
        };
        /** SourceInfo */
        SourceInfo: {
            /** Domain */
            domain: string | null;
            /** Key */
            key: string;
            /** Name */
            name: string;
            reliability: components["schemas"]["Reliability"];
            /** Type */
            type: string;
        };
        /** SourceLinkOut */
        SourceLinkOut: {
            /** Access */
            access?: ("free" | "free_account" | "licence" | "subscription") | null;
            /** Available */
            available?: boolean | null;
            /** Confirmed */
            confirmed?: boolean | null;
            /** Coverage */
            coverage?: ("all" | "selected") | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Health
             * @enum {string}
             */
            health: "working" | "checking" | "unverified" | "offline";
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Language */
            language: string | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Link Type */
            link_type: string;
            /** Message */
            message: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * One Click
             * @default false
             */
            one_click: boolean;
            /** Quality */
            quality: string | null;
            /** Redirect Hops */
            redirect_hops: number;
            /** Regions */
            regions?: string[] | null;
            /** Response Time Ms */
            response_time_ms: number | null;
            source: components["schemas"]["SourceInfo"];
            /** Status */
            status: string;
            /** Watch Url */
            watch_url: string | null;
        };
        /** SourcePatch */
        SourcePatch: {
            /** Enabled */
            enabled: boolean;
        };
        /** SourceSummary */
        SourceSummary: {
            /**
             * Checking
             * @default 0
             */
            checking: number;
            /**
             * Offline
             * @default 0
             */
            offline: number;
            top?: components["schemas"]["TopSource"] | null;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Unverified
             * @default 0
             */
            unverified: number;
            /**
             * Working
             * @default 0
             */
            working: number;
        };
        /** StatOut */
        StatOut: {
            /** Away */
            away: number;
            /** Home */
            home: number;
            /**
             * Key
             * @enum {string}
             */
            key: "possession" | "shots" | "shots_on_target" | "corners" | "passes" | "pass_accuracy" | "fouls" | "offsides" | "saves" | "yellow_cards" | "red_cards";
            /**
             * Unit
             * @default
             * @enum {string}
             */
            unit: "" | "%";
        };
        /** TableGroup */
        TableGroup: {
            /** Name */
            name: string | null;
            /** Rows */
            rows: components["schemas"]["TableRow"][];
        };
        /** TableNote */
        TableNote: {
            /** Color */
            color: string | null;
            /** Label */
            label: string;
        };
        /** TableOut */
        TableOut: {
            /** Available */
            available: boolean;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["TableGroup"][];
            /**
             * Legend
             * @default []
             */
            legend: components["schemas"]["TableNote"][];
            /** Season */
            season?: string | null;
        };
        /** TableRow */
        TableRow: {
            /** Drawn */
            drawn: number;
            /** Goal Difference */
            goal_difference: number;
            /** Goals Against */
            goals_against: number;
            /** Goals For */
            goals_for: number;
            /** Logo Url */
            logo_url: string | null;
            /** Lost */
            lost: number;
            /** Name */
            name: string;
            note?: components["schemas"]["TableNote"] | null;
            /** Played */
            played: number;
            /** Points */
            points: number;
            /** Rank */
            rank: number;
            /** Short Name */
            short_name: string | null;
            team: components["schemas"]["TeamOut"] | null;
            /** Won */
            won: number;
        };
        /** TeamDetailOut */
        TeamDetailOut: {
            /** Country */
            country: string | null;
            /** Id */
            id: number;
            /** Logo Url */
            logo_url: string | null;
            media: components["schemas"]["TeamMediaOut"];
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string | null;
            /** Secondary Color */
            secondary_color: string | null;
            /** Short Name */
            short_name: string | null;
            /** Slug */
            slug: string;
            /** Tla */
            tla: string | null;
        };
        /** TeamMediaOut */
        TeamMediaOut: {
            /** Capacity */
            capacity?: number | null;
            /** Founded */
            founded?: number | null;
            photo?: components["schemas"]["PhotoOut"] | null;
            /** Stadium */
            stadium?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ok" | "partial" | "none" | "error";
            /** Website */
            website?: string | null;
        };
        /** TeamOut */
        TeamOut: {
            /** Country */
            country: string | null;
            /** Id */
            id: number;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string | null;
            /** Secondary Color */
            secondary_color: string | null;
            /** Short Name */
            short_name: string | null;
            /** Slug */
            slug: string;
            /** Tla */
            tla: string | null;
        };
        /** TopSource */
        TopSource: {
            /** Access */
            access?: ("free" | "free_account" | "licence" | "subscription") | null;
            /** Available */
            available?: boolean | null;
            /** Label */
            label: string;
            /**
             * One Click
             * @default false
             */
            one_click: boolean;
            /** Type */
            type: string;
            /** Watch Url */
            watch_url?: string | null;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Link Ids */
            link_ids?: number[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_api_admin_check_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    links_api_admin_links_get: {
        parameters: {
            query?: {
                health?: string | null;
                source?: string | null;
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_matches_api_admin_matches_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_admin_runs_get: {
        parameters: {
            query?: {
                job?: string | null;
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_admin_sources__key__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    competitions_api_competitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionWithCounts"][];
                };
            };
        };
    };
    competition_detail_api_competitions__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    competition_table_api_competitions__slug__table_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: {
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_links_api_links_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_api_matches_get: {
        parameters: {
            query?: {
                status?: "live" | "upcoming" | "finished" | "all";
                date_from?: string | null;
                date_to?: string | null;
                competition?: string | null;
                team?: string | null;
                /** @description Comma-separated team slugs */
                teams?: string | null;
                limit?: number;
                offset?: number;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_matches_api_matches_live_get: {
        parameters: {
            query?: {
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_matches_api_matches_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_matches_api_matches_upcoming_get: {
        parameters: {
            query?: {
                days?: number;
                competition?: string | null;
                limit?: number;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_detail_api_matches__ref__get: {
        parameters: {
            query?: {
                country?: string | null;
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_details_api_matches__ref__details_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_sources_api_matches__ref__sources_get: {
        parameters: {
            query?: {
                country?: string | null;
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSources"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_sources_api_sources_run_post: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teams_api_teams_get: {
        parameters: {
            query?: {
                competition?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_detail_api_teams__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
